### ISSUE TITLE
GetAtt on Uluru resource types only works with readOnlyProperties 

### ISSUE THREAD

**Issue by yangmarc** [aws-cloudformation/aws-cloudformation-resource-providers-sns#33]
See https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/68 for customer feedback.

According to the official documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html#aws-properties-sns-topic-return-values

Fn::GetAtt for `TopicName` will not work as `TopicName` is not ReadOnlyProperties

**Comment by shih** [comment]
We've got internal confirmation that this is no longer a blocker for sns Uluru launch.

**Comment by yangmarc** [comment]
Congrats!

**Comment by shih** [comment]
> Congrats!

Credits to all previous work of @yangmarc .
