### ISSUE TITLE
AWS::SNS::Topic - DeliveryStatusLogging

### ISSUE THREAD

**Issue by rdbatch02** [aws-cloudformation/aws-cloudformation-resource-providers-sns#86]
This issue was raised on the CloudFormation roadmap repo back in 2019 https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/66. 

Delivery Status Logging has been supported by SNS for over 8 years and has support in the language SDKs, but no support in CloudFormation. This could be added as a new attribute that would default to empty (no delivery status logging) and should not require replacement since updating the attributes using the SDK can be done without creating a new resource.

**Comment by shih** [comment]
This has been launched. 
https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-sns-configuring-delivery-status-logging-aws-cloudformation/
We'll sync the launch code to GH soon.
